---
name: Omada Controller Stable NO-AVX
image: jeruntu/home-assistant-omada-stable-no-avx
version: 6.1.0.19
slug: omada_controller_stable_no_avx
description: TP-Link Omada Controller software (No AVX support for older CPUs)
webui: https://[HOST]:[PORT:8043]
startup: application
arch:
  - aarch64
  - amd64
init: false
url: https://github.com/jkunczik/home-assistant-omada
map:
  - ssl
options:
  enable_hass_ssl: false
  certfile: /ssl/fullchain.pem
  keyfile: /ssl/privkey.pem
  upgrade_https_port: 8043
  show_mongodb_logs: false
  show_server_logs: true
schema:
  enable_hass_ssl: bool
  certfile: str
  keyfile: str
  upgrade_https_port: int
  show_mongodb_logs: bool
  show_server_logs: bool
host_network: true
