name: Build Docker Image

on:
  push:
    branches-ignore:
      - master

jobs:
  build-dev-no-push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: ["dev", "no-avx"]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Build Variables
        run: |
          TARGET="${{ matrix.target }}"

          if [[ "$TARGET" == "no-avx" ]]; then
            echo "CONFIG_FILE=Omada Stable v6 NO-AVX/config.yaml" >> $GITHUB_ENV
            echo "DOCKERFILE=./Omada Dev/noavx.dockerfile" >> $GITHUB_ENV
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
            echo "TAG_PREFIX=home-assistant-omada-v6-no-avx" >> $GITHUB_ENV
          else
            echo "CONFIG_FILE=Omada Dev/config.yaml" >> $GITHUB_ENV
            echo "DOCKERFILE=./Omada Dev/Dockerfile" >> $GITHUB_ENV
            echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV
            echo "TAG_PREFIX=home-assistant-omada-dev" >> $GITHUB_ENV
          fi

      - name: Extract Version
        id: extract_version
        run: |
          VERSION_HA=$(yq '.version' "${{ env.CONFIG_FILE }}")
          VERSION_OMADA=$(echo $VERSION_HA | sed -E 's/-ha[0-9]+$//')
          echo "VERSION_OMADA=$VERSION_OMADA" >> $GITHUB_ENV
          echo "Docker Tag: $VERSION_OMADA"

      - name: Check Omada Version Availability
        uses: ./.github/actions/version-checks
        with:
          version: "${{ env.VERSION_OMADA }}"

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform "${{ env.PLATFORMS }}" \
            --file "${{ env.DOCKERFILE }}" \
            --tag "${{ env.TAG_PREFIX }}:${{ env.VERSION_OMADA }}" \
            --build-arg INSTALL_VER="${{ env.VERSION_OMADA }}" \
            "./Omada Dev"